### ISSUE TITLE
photos without exif data

### ISSUE THREAD

**Issue by SvenSvensen** [pinae/photo-sorter-script#3]
Hello,
script works fine.
If there are photos without exif data inside input folder, I get this error:
The file D:/111/xxx\DVLS8105.JPGhas no exif data.
Traceback (most recent call last):
  File "imagesbyday.py", line 46, in <module>
    day_str = image_time.strftime("%Y_%m_%d")
AttributeError: 'float' object has no attribute 'strftime'

The script stopped. All photos after this will not be renamed
What's the problem ?

**Comment by pinae** [comment]
Hi,

your photo contains no exif data at all.

You could catch this Exception and fall back to the modification date of the file. I will not add this error handling to my code because it would make it longer and harder to read. However feel free to fork.

Yours,
  Pina

**Comment by SvenSvensen** [comment]
Hello,
thx for your answer.
You already do some error handling inside the script, like  ... has no exif data.
This error handling does not work correctly, see the error message "AttributeError: 'float' object has no attribute 'strftime'".
I did already some code changes but doesn't fix the problem. I'm not a programmer

best regards
Sven
